name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[release]') }}
    steps:
      - uses: actions/checkout@v2
      - uses: ArnaudBarre/github-release@v1
